# Site settings
title: Your awesome title
email: your-email@domain.com
description: Electric Cloud Opensource
baseurl: "/jekyll-test" # the subpath of your site, e.g. /blog/
url: "http://electric-cloud.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
